/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package nz.org.take.script.parser;

public interface ParserConstants {

  int EOF = 0;
  int DOT = 5;
  int VAR = 6;
  int CON = 7;
  int RULES = 8;
  int AND = 9;
  int IF = 10;
  int THEN = 11;
  int INTEGER_NUMBER = 12;
  int DECIMAL_NUMBER = 13;
  int NAME = 14;
  int STRING = 15;
  int WHITESPACE = 16;
  int SEMICOLON = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\".\"",
    "\"var\"",
    "\"constant\"",
    "\"rules\"",
    "\"and\"",
    "\"if\"",
    "\"then\"",
    "<INTEGER_NUMBER>",
    "<DECIMAL_NUMBER>",
    "<NAME>",
    "<STRING>",
    "<WHITESPACE>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
