package test.nz.org.take.compiler.scenario0.generatedclasses;
/**
 * Class generated by the take compiler. 
 * This class holds the expressions referenced in the knowledge base. 
 * @version Wed Jul 29 22:27:06 NZST 2009
 */
@SuppressWarnings("unchecked")
public class Expressions{
// compiled expression: x=='jens'
static Object expression1 = org.mvel2.MVEL.compileExpression("x=='jens'");
}
