//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.18 at 02:02:18 PM NZST 
//


package nz.org.take.xml.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nz.org.take.xml.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BodyatomExpression_QNAME = new QName("http://code.google.com/p/take", "expression");
    private final static QName _BodyatomRef_QNAME = new QName("http://code.google.com/p/take", "ref");
    private final static QName _BodyatomVar_QNAME = new QName("http://code.google.com/p/take", "var");
    private final static QName _RuleSet_QNAME = new QName("http://code.google.com/p/take", "rule-set");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nz.org.take.xml.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Bodyatom }
     * 
     */
    public Bodyatom createBodyatom() {
        return new Bodyatom();
    }

    /**
     * Create an instance of {@link Var }
     * 
     */
    public Var createVar() {
        return new Var();
    }

    /**
     * Create an instance of {@link Ref }
     * 
     */
    public Ref createRef() {
        return new Ref();
    }

    /**
     * Create an instance of {@link Slot }
     * 
     */
    public Slot createSlot() {
        return new Slot();
    }

    /**
     * Create an instance of {@link Then }
     * 
     */
    public Then createThen() {
        return new Then();
    }

    /**
     * Create an instance of {@link Query }
     * 
     */
    public Query createQuery() {
        return new Query();
    }

    /**
     * Create an instance of {@link RuleSet }
     * 
     */
    public RuleSet createRuleSet() {
        return new RuleSet();
    }

    /**
     * Create an instance of {@link If }
     * 
     */
    public If createIf() {
        return new If();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link Atom }
     * 
     */
    public Atom createAtom() {
        return new Atom();
    }

    /**
     * Create an instance of {@link Rule }
     * 
     */
    public Rule createRule() {
        return new Rule();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://code.google.com/p/take", name = "expression", scope = Bodyatom.class)
    public JAXBElement<String> createBodyatomExpression(String value) {
        return new JAXBElement<String>(_BodyatomExpression_QNAME, String.class, Bodyatom.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://code.google.com/p/take", name = "ref", scope = Bodyatom.class)
    @XmlIDREF
    public JAXBElement<Object> createBodyatomRef(Object value) {
        return new JAXBElement<Object>(_BodyatomRef_QNAME, Object.class, Bodyatom.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://code.google.com/p/take", name = "var", scope = Bodyatom.class)
    @XmlIDREF
    public JAXBElement<Object> createBodyatomVar(Object value) {
        return new JAXBElement<Object>(_BodyatomVar_QNAME, Object.class, Bodyatom.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RuleSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://code.google.com/p/take", name = "rule-set")
    public JAXBElement<RuleSet> createRuleSet(RuleSet value) {
        return new JAXBElement<RuleSet>(_RuleSet_QNAME, RuleSet.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://code.google.com/p/take", name = "ref", scope = Atom.class)
    @XmlIDREF
    public JAXBElement<Object> createAtomRef(Object value) {
        return new JAXBElement<Object>(_BodyatomRef_QNAME, Object.class, Atom.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://code.google.com/p/take", name = "var", scope = Atom.class)
    @XmlIDREF
    public JAXBElement<Object> createAtomVar(Object value) {
        return new JAXBElement<Object>(_BodyatomVar_QNAME, Object.class, Atom.class, value);
    }

}
