//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.18 at 02:02:18 PM NZST 
//


package nz.org.take.xml.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rule-set complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rule-set">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;element name="annotation" type="{http://code.google.com/p/take}annotation"/>
 *           &lt;element name="var" type="{http://code.google.com/p/take}var"/>
 *           &lt;element name="ref" type="{http://code.google.com/p/take}ref"/>
 *           &lt;element name="rule" type="{http://code.google.com/p/take}rule"/>
 *           &lt;element name="query" type="{http://code.google.com/p/take}query"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rule-set", propOrder = {
    "annotationOrVarOrRef"
})
public class RuleSet {

    @XmlElements({
        @XmlElement(name = "ref", type = Ref.class),
        @XmlElement(name = "annotation", type = Annotation.class),
        @XmlElement(name = "rule", type = Rule.class),
        @XmlElement(name = "var", type = Var.class),
        @XmlElement(name = "query", type = Query.class)
    })
    protected List<Object> annotationOrVarOrRef;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the annotationOrVarOrRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotationOrVarOrRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotationOrVarOrRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ref }
     * {@link Annotation }
     * {@link Rule }
     * {@link Var }
     * {@link Query }
     * 
     * 
     */
    public List<Object> getAnnotationOrVarOrRef() {
        if (annotationOrVarOrRef == null) {
            annotationOrVarOrRef = new ArrayList<Object>();
        }
        return this.annotationOrVarOrRef;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
