package example.nz.org.take.compiler.example1.spec;

/**
 * Class generated by the mandarax compiler.
 * @version Sun May 27 22:18:54 NZST 2007
 */
public class CustomerDiscount {
    public test.nz.org.take.compiler.scenario5.Customer customer;
    public test.nz.org.take.compiler.scenario5.Discount discount;

    public CustomerDiscount(
        test.nz.org.take.compiler.scenario5.Customer customer,
        test.nz.org.take.compiler.scenario5.Discount discount) {
        super();
        this.customer = customer;
        this.discount = discount;
    }

    public CustomerDiscount() {
        super();
    }
}
