package example.nz.org.take.compiler.example1.spec;

/**
 * Class generated by the mandarax compiler.
 * @version Mon May 28 14:15:20 NZST 2007
 */
public class CustomerDiscount {
    public example.nz.org.take.compiler.example1.Customer customer;
    public example.nz.org.take.compiler.example1.Discount discount;

    public CustomerDiscount(
        example.nz.org.take.compiler.example1.Customer customer,
        example.nz.org.take.compiler.example1.Discount discount) {
        super();
        this.customer = customer;
        this.discount = discount;
    }

    public CustomerDiscount() {
        super();
    }
}
