package example.nz.org.take.compiler.example1.spec;

/**
 * Class generated by the mandarax compiler.
 * @version Wed May 23 20:51:57 NZST 2007
 */
public class IsFatherOf {
    public example.nz.org.take.compiler.example1.Person son;
    public example.nz.org.take.compiler.example1.Person father;

    public IsFatherOf(example.nz.org.take.compiler.example1.Person son,
        example.nz.org.take.compiler.example1.Person father) {
        super();
        this.son = son;
        this.father = father;
    }

    public IsFatherOf() {
        super();
    }
}
