package example.nz.org.take.compiler.example1.spec;

/**
 * Class generated by the mandarax compiler.
 * @version Sun May 20 22:39:32 NZST 2007
 */
public class IsFatherOf {
    public test.nz.org.take.compiler.scenario6.Person son;
    public test.nz.org.take.compiler.scenario6.Person father;

    IsFatherOf(test.nz.org.take.compiler.scenario6.Person son,
        test.nz.org.take.compiler.scenario6.Person father) {
        super();
        this.son = son;
        this.father = father;
    }

    IsFatherOf() {
        super();
    }
}
