package example.nz.org.take.compiler.example1.spec;

/**
 * Class generated by the mandarax compiler.
 * @version Sun May 20 22:39:34 NZST 2007
 */
public class IsGrandfatherOf {
    public test.nz.org.take.compiler.scenario6.Person grandson;
    public test.nz.org.take.compiler.scenario6.Person grandfather;

    IsGrandfatherOf(test.nz.org.take.compiler.scenario6.Person grandson,
        test.nz.org.take.compiler.scenario6.Person grandfather) {
        super();
        this.grandson = grandson;
        this.grandfather = grandfather;
    }

    IsGrandfatherOf() {
        super();
    }
}
