package example.nz.org.take.compiler.userv.spec;

/**
 * Class generated by the take compiler.
 * This class represents the predicate additionalPremium
 * @version Thu Oct 18 23:01:31 NZDT 2007
 */
public class AdditionalPremium {
    public example.nz.org.take.compiler.userv.domainmodel.Policy policy;
    public example.nz.org.take.compiler.userv.domainmodel.Car car;
    public int premium;

    public AdditionalPremium(
        example.nz.org.take.compiler.userv.domainmodel.Policy policy,
        example.nz.org.take.compiler.userv.domainmodel.Car car, int premium) {
        super();
        this.policy = policy;
        this.car = car;
        this.premium = premium;
    }

    public AdditionalPremium() {
        super();
    }
}
