package example.nz.org.take.compiler.userv.spec;

/**
 * Class generated by the take compiler.
 * This class represents the predicate potentialOccupantInjuryRating
 * @version Sun Oct 21 23:25:20 NZDT 2007
 */
public class PotentialOccupantInjuryRating {
    public example.nz.org.take.compiler.userv.domainmodel.Car car;
    public java.lang.String rating;

    public PotentialOccupantInjuryRating(
        example.nz.org.take.compiler.userv.domainmodel.Car car,
        java.lang.String rating) {
        super();
        this.car = car;
        this.rating = rating;
    }

    public PotentialOccupantInjuryRating() {
        super();
    }
}
