package example.nz.org.take.compiler.userv.spec;

/**
 * Class generated by the take compiler.
 * This class represents the predicate potentialTheftRating
 * @version Fri Oct 19 20:57:30 NZDT 2007
 */
public class PotentialTheftRating {
    public example.nz.org.take.compiler.userv.domainmodel.Car car;
    public java.lang.String rating;

    public PotentialTheftRating(
        example.nz.org.take.compiler.userv.domainmodel.Car car,
        java.lang.String rating) {
        super();
        this.car = car;
        this.rating = rating;
    }

    public PotentialTheftRating() {
        super();
    }
}
