package example.nz.org.take.compiler.userv.spec;

/**
 * Class generated by the take compiler.
 * This class represents the predicate premiumDiscount
 * @version Fri Oct 19 20:57:30 NZDT 2007
 */
public class PremiumDiscount {
    public example.nz.org.take.compiler.userv.domainmodel.Car car;
    public int discount;

    public PremiumDiscount(
        example.nz.org.take.compiler.userv.domainmodel.Car car, int discount) {
        super();
        this.car = car;
        this.discount = discount;
    }

    public PremiumDiscount() {
        super();
    }
}
