package test.nz.org.take.compiler.scenario0.generatedclasses;

/**
 * Class generated by the take compiler.
 * This class represents the predicate son
 * @version Mon Oct 12 12:39:34 NZDT 2009
 */
public class son {
    public java.lang.String father;
    public java.lang.String son;

    public son(java.lang.String father, java.lang.String son) {
        super();
        this.father = father;
        this.son = son;
    }

    public son() {
        super();
    }
}
