package example.nz.org.take.compiler.example1.spec;

import nz.org.take.rt.*;


/**
 * Interface generated by the take compiler.
 * @version Tue Sep 18 22:06:49 NZST 2007
 */
@SuppressWarnings("unchecked")
public interface DiscountPolicy {
    /**
     * Method generated for query /discount[in,out]
     * @param customer input parameter generated from slot 0
     * @return an iterator for instances of CustomerDiscount
    */
    public ResultSet<CustomerDiscount> getDiscount(
        final example.nz.org.take.compiler.example1.Customer customer);

    /**
    * Method that can be used to query annotations at runtime.
    * @param id the id of the rule (or other knowledge element)
    * @return a map of annotations (string-string mappings)
    * code generated using velocity template AnnotationMethod.vm
    */
    public java.util.Map<String, String> getAnnotations(String id);
}
