package example.nz.org.take.compiler.example1.spec;

import nz.org.take.rt.*;


/**
 * Interface generated by the take compiler.
 * @version Fri Feb 01 10:12:41 NZDT 2008
 */
@SuppressWarnings("unchecked")
public interface DiscountPolicy {
    /**
     * Method generated for query /discount[in,out]
     * @param customer input parameter generated from slot 0
     * @return an iterator for instances of CustomerDiscount
    */
    public ResultSet<CustomerDiscount> getDiscount(
        final example.nz.org.take.compiler.example1.Customer customer);

    /**
    * Method that can be used to query annotations at runtime.
    * @param id the id of the rule (or other knowledge element)
    * @return a map of annotations (string-string mappings)
    * code generated using velocity template LocalAnnotationMethod.vm
    */
    public java.util.Map<String, String> getAnnotations(String id);

    /**
     * Method that can be used to query global annotations at runtime.
     * Global annotations are attached to the knowledge base, not to
     * a particular element (rule,..).
     * @return a map of annotations (string-string mappings)
     * code generated using velocity template GlobalAnnotationMethod.vm
    */
    public java.util.Map<String, String> getAnnotations();
}
