package example.nz.org.take.compiler.userv.spec.impl_v071107_031153;
import example.nz.org.take.compiler.userv.spec.*;
/**
 * Class generated by the take compiler. 
 * In this class the aggregation functions referenced in the knowledge base are defined. 
 * @version Wed Nov 07 03:11:53 GMT 2007
 */
@SuppressWarnings("unchecked")
public class Aggregations{
    /**
     * Method generated for aggregation function eligibilityScore
     * code generated using velocity template AggregationFunctionSUM.vm
    */
    public static int eligibilityScore (example.nz.org.take.compiler.userv.domainmodel.Car arg0,example.nz.org.take.compiler.userv.domainmodel.Driver arg1) {
        
        int _value = 0;
        nz.org.take.rt.ResultSet<PolicyEligibilityScore> _result = KBFragement_getPolicyEligibilityScore.getPolicyEligibilityScore(arg0,arg1);
        while (_result.hasNext()) {
        	_value = _value + _result.next().score;
        } 
        _result.close();
        return _value;
    }}
