package example.nz.org.take.compiler.userv.spec.impl_v071107_031153;

/**
 * Class generated by the take compiler.
 * This class represents the predicate greater_than_or_equal_ii
 * @version Wed Nov 07 03:11:54 GMT 2007
 */
public class greater_than_or_equal_ii {
    public int slot1;
    public int slot2;

    public greater_than_or_equal_ii(int slot1, int slot2) {
        super();
        this.slot1 = slot1;
        this.slot2 = slot2;
    }

    public greater_than_or_equal_ii() {
        super();
    }
}
