package example.nz.org.take.compiler.userv.spec.impl_v071107_031153;

import example.nz.org.take.compiler.userv.spec.*;

import nz.org.take.rt.*;


/**
 * Class generated by the take compiler.
 * @version Wed Nov 07 03:11:56 GMT 2007
 */
@SuppressWarnings("unchecked")
class KBFragement_hasAirbags_1 {
    /**
     * Method generated for query hasAirbags[in]
     * @param slot1 input parameter generated from slot 0
     * @return an iterator for instances of hasAirbags
    */
    public static ResultSet<hasAirbags> hasAirbags_1(
        final example.nz.org.take.compiler.userv.domainmodel.Car slot1) {
        DerivationController _derivation = new DefaultDerivationController();
        ResultSet<hasAirbags> _result = new ResultSet(KBFragement_hasAirbags_1.hasAirbags_1(
                    slot1, _derivation), _derivation);

        return _result;
    }

    /**
     * Method generated for query hasAirbags[in]
     * @param source
     * @param target
     * @return an iterator
     * code generated using velocity template JPredicate_11.vm
    */
    static ResourceIterator<hasAirbags> hasAirbags_1(
        final example.nz.org.take.compiler.userv.domainmodel.Car slot1,
        final DerivationController _derivation) {
        _derivation.log("public boolean example.nz.org.take.compiler.userv.domainmodel.Car.hasAirbags()",
            DerivationController.JAVA_METHOD);

        if (slot1.hasAirbags()) {
            hasAirbags result = new hasAirbags();
            result.slot1 = slot1;

            return new SingletonIterator<hasAirbags>(result);
        }

        return EmptyIterator.DEFAULT;
    }
}
