package example.nz.org.take.compiler.userv.spec.impl_v071107_031153;

/**
 * Class generated by the take compiler.
 * This class represents the predicate specialLocation
 * @version Wed Nov 07 03:11:54 GMT 2007
 */
public class not_specialLocation {
    public example.nz.org.take.compiler.userv.domainmodel.Driver slot1;

    public not_specialLocation(
        example.nz.org.take.compiler.userv.domainmodel.Driver slot1) {
        super();
        this.slot1 = slot1;
    }

    public not_specialLocation() {
        super();
    }
}
