/*
 * Copyright (C) 2006 <A href="http://www-ist.massey.ac.nz/JBDietrich" target="_top">Jens Dietrich</a>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */


package test01.org.mandarax.compiler.prototype;

import org.apache.log4j.BasicConfigurator;
import org.mandarax.compiler.CompilerFactory;
import org.mandarax.compiler.NameGenerator;
import org.mandarax.compiler.util.DefaultLocation;
import org.mandarax.compiler.util.DefaultNameGenerator;
import org.mandarax.compiler.util.jalopy.JalopyCodeFormatter;

import test.nz.org.take.compiler.scenario1.KBFactory;

/**
 * Script to generate classes from the kb generated by KBFactory.
 * @see KBFactory
 * @author <a href="http://www-ist.massey.ac.nz/JBDietrich/">Jens Dietrich</a>
 * @version 0.1
 */

public class GenerateClasses {

	/**
	 * Generate the sources for the example.
	 * @param args
	 */
	public static void main(String[] args) throws Exception {
		BasicConfigurator.configure();
		DefaultLocation location = new DefaultLocation();
		NameGenerator nameGenerator = new DefaultNameGenerator();
		org.mandarax.compiler.Compiler compiler = CompilerFactory.getCompiler();
		compiler.add(new JalopyCodeFormatter());
		compiler.setNameGenerator(nameGenerator);
		KBFactory fact = new KBFactory();
		
		compiler.compile(fact.kb(),fact.queries(), location, "test01.org.mandarax.compiler.prototype.generated","_KB");

	}

}
