package example.nz.org.take.compiler.example1.spec;

/**
 * Class generated by the take compiler.
 * This class represents the predicate discount
 * @version Tue Sep 18 22:06:48 NZST 2007
 */
public class CustomerDiscount {
    public example.nz.org.take.compiler.example1.Customer customer;
    public example.nz.org.take.compiler.example1.Discount discount;

    public CustomerDiscount(
        example.nz.org.take.compiler.example1.Customer customer,
        example.nz.org.take.compiler.example1.Discount discount) {
        super();
        this.customer = customer;
        this.discount = discount;
    }

    public CustomerDiscount() {
        super();
    }
}
