package example.nz.org.take.compiler.example1.spec;

/**
 * Class generated by the mandarax compiler.
 * @version Wed May 23 20:52:05 NZST 2007
 */
public class IsGrandfatherOf {
    public example.nz.org.take.compiler.example1.Person grandson;
    public example.nz.org.take.compiler.example1.Person grandfather;

    public IsGrandfatherOf(
        example.nz.org.take.compiler.example1.Person grandson,
        example.nz.org.take.compiler.example1.Person grandfather) {
        super();
        this.grandson = grandson;
        this.grandfather = grandfather;
    }

    public IsGrandfatherOf() {
        super();
    }
}
