package example.nz.org.take.compiler.userv.spec.impl_v071107_031153;
/**
 * Class generated by the take compiler. 
 * This class holds the constants referenced in the knowledge base. 
 * @version Wed Nov 07 03:11:53 GMT 2007
 */
@SuppressWarnings("unchecked")
public class Constants{
public static int CurrentYear;
public static java.util.Collection HighTheftProbabilityAutoList;
public static int NextYear;
}
