package example.nz.org.take.compiler.userv.spec.impl_v071107_031153;

/**
 * Class generated by the take compiler.
 * This class represents the predicate includesMedicalCoverage
 * @version Wed Nov 07 03:11:54 GMT 2007
 */
public class includesMedicalCoverage {
    public example.nz.org.take.compiler.userv.domainmodel.Policy slot1;

    public includesMedicalCoverage(
        example.nz.org.take.compiler.userv.domainmodel.Policy slot1) {
        super();
        this.slot1 = slot1;
    }

    public includesMedicalCoverage() {
        super();
    }
}
