package example.nz.org.take.compiler.userv.spec.impl_v071107_031153;

import example.nz.org.take.compiler.userv.spec.*;

import nz.org.take.rt.*;


/**
 * Class generated by the take compiler.
 * @version Wed Nov 07 03:11:56 GMT 2007
 */
@SuppressWarnings("unchecked")
class KBFragement_specialLocation_1 {
    /**
     * Method generated for query /specialLocation[in]
     * @param slot1 input parameter generated from slot 0
     * @return an iterator for instances of specialLocation
    */
    public static ResultSet<specialLocation> specialLocation_1(
        final example.nz.org.take.compiler.userv.domainmodel.Driver slot1) {
        DerivationController _derivation = new DefaultDerivationController();
        ResultSet<specialLocation> _result = new ResultSet(KBFragement_specialLocation_1.specialLocation_1(
                    slot1, _derivation), _derivation);

        return _result;
    }

    /**
     * Method generated for query /specialLocation[in]
     * @param slot1 input parameter generated from slot 0
     * @return an iterator for instances of specialLocation
    */
    static ResourceIterator<specialLocation> specialLocation_1(
        final example.nz.org.take.compiler.userv.domainmodel.Driver slot1,
        final DerivationController _derivation) {
        final int _derivationlevel = _derivation.getDepth();
        ResourceIterator<specialLocation> result = new IteratorChain<specialLocation>(1) {
                public Object getIteratorOrObject(int pos) {
                    switch (pos) {
                    // DP_00x nz.org.take.ExternalFactStore@100bac2
                    case 0:
                        return specialLocation_1_0(slot1,
                            _derivation.reset(_derivationlevel));

                    default:
                        return EmptyIterator.DEFAULT;
                    } // switch(pos)
                } // getIterator()

                public String getRuleRef(int pos) {
                    switch (pos) {
                    // DP_00x nz.org.take.ExternalFactStore@100bac2
                    case 0:
                        return "DP_00x";

                    default:
                        return "";
                    } // switch(pos)
                } // getRuleRef()
            };

        return result;
    }

    /**
     * Method generated for query /specialLocation[in]
     * @param slot1 input parameter generated from slot 0
     * @return an iterator for instances of specialLocation
    */
    private static ResourceIterator<specialLocation> specialLocation_1_0(
        final example.nz.org.take.compiler.userv.domainmodel.Driver slot1,
        final DerivationController _derivation) {
        _derivation.log("DP_00x", DerivationController.EXTERNAL_FACT_SET, slot1);

        return FactStores.DP_00x.fetch(slot1);
    }
}
