package example.nz.org.take.compiler.userv.spec.impl_v071107_031153;

import example.nz.org.take.compiler.userv.spec.*;

import nz.org.take.rt.*;


/**
 * Class generated by the take compiler.
 * @version Wed Nov 07 03:11:56 GMT 2007
 */
@SuppressWarnings("unchecked")
class KBFragement_hasBeenConvictedOfaDUI_1 {
    /**
     * Method generated for query /hasBeenConvictedOfaDUI[in]
     * @param slot1 input parameter generated from slot 0
     * @return an iterator for instances of hasBeenConvictedOfaDUI
    */
    public static ResultSet<hasBeenConvictedOfaDUI> hasBeenConvictedOfaDUI_1(
        final example.nz.org.take.compiler.userv.domainmodel.Driver slot1) {
        DerivationController _derivation = new DefaultDerivationController();
        ResultSet<hasBeenConvictedOfaDUI> _result = new ResultSet(KBFragement_hasBeenConvictedOfaDUI_1.hasBeenConvictedOfaDUI_1(
                    slot1, _derivation), _derivation);

        return _result;
    }

    /**
     * Method generated for query /hasBeenConvictedOfaDUI[in]
     * @param slot1 input parameter generated from slot 0
     * @return an iterator for instances of hasBeenConvictedOfaDUI
    */
    static ResourceIterator<hasBeenConvictedOfaDUI> hasBeenConvictedOfaDUI_1(
        final example.nz.org.take.compiler.userv.domainmodel.Driver slot1,
        final DerivationController _derivation) {
        final int _derivationlevel = _derivation.getDepth();
        ResourceIterator<hasBeenConvictedOfaDUI> result = new IteratorChain<hasBeenConvictedOfaDUI>(1) {
                public Object getIteratorOrObject(int pos) {
                    switch (pos) {
                    // DRCx nz.org.take.ExternalFactStore@53ab04
                    case 0:
                        return hasBeenConvictedOfaDUI_1_0(slot1,
                            _derivation.reset(_derivationlevel));

                    default:
                        return EmptyIterator.DEFAULT;
                    } // switch(pos)
                } // getIterator()

                public String getRuleRef(int pos) {
                    switch (pos) {
                    // DRCx nz.org.take.ExternalFactStore@53ab04
                    case 0:
                        return "DRCx";

                    default:
                        return "";
                    } // switch(pos)
                } // getRuleRef()
            };

        return result;
    }

    /**
     * Method generated for query /hasBeenConvictedOfaDUI[in]
     * @param slot1 input parameter generated from slot 0
     * @return an iterator for instances of hasBeenConvictedOfaDUI
    */
    private static ResourceIterator<hasBeenConvictedOfaDUI> hasBeenConvictedOfaDUI_1_0(
        final example.nz.org.take.compiler.userv.domainmodel.Driver slot1,
        final DerivationController _derivation) {
        _derivation.log("DRCx", DerivationController.EXTERNAL_FACT_SET, slot1);

        return FactStores.DRCx.fetch(slot1);
    }
}
