package example.nz.org.take.compiler.userv.spec.impl_v071107_031153;

/**
 * Class generated by the take compiler.
 * This class represents the predicate driverCategory
 * @version Wed Nov 07 03:11:54 GMT 2007
 */
public class not_DriverCategory {
    public example.nz.org.take.compiler.userv.domainmodel.Driver driver;
    public java.lang.String category;

    public not_DriverCategory(
        example.nz.org.take.compiler.userv.domainmodel.Driver driver,
        java.lang.String category) {
        super();
        this.driver = driver;
        this.category = category;
    }

    public not_DriverCategory() {
        super();
    }
}
