package example.nz.org.take.compiler.userv.spec;

/**
 * Class generated by the take compiler.
 * This class represents the predicate autoEligibility
 * @version Thu Oct 18 23:01:31 NZDT 2007
 */
public class AutoEligibility {
    public example.nz.org.take.compiler.userv.domainmodel.Car car;
    public java.lang.String value;

    public AutoEligibility(
        example.nz.org.take.compiler.userv.domainmodel.Car car,
        java.lang.String value) {
        super();
        this.car = car;
        this.value = value;
    }

    public AutoEligibility() {
        super();
    }
}
