package example.nz.org.take.compiler.userv.spec;

/**
 * Class generated by the take compiler.
 * This class represents the predicate basePremium
 * @version Sun Oct 21 23:25:20 NZDT 2007
 */
public class BasePremium {
    public example.nz.org.take.compiler.userv.domainmodel.Car car;
    public int premium;

    public BasePremium(example.nz.org.take.compiler.userv.domainmodel.Car car,
        int premium) {
        super();
        this.car = car;
        this.premium = premium;
    }

    public BasePremium() {
        super();
    }
}
