package example.nz.org.take.compiler.userv.spec;

/**
 * Class generated by the take compiler.
 * This class represents the predicate driverCategory
 * @version Fri Oct 19 20:57:30 NZDT 2007
 */
public class DriverCategory {
    public example.nz.org.take.compiler.userv.domainmodel.Driver driver;
    public java.lang.String category;

    public DriverCategory(
        example.nz.org.take.compiler.userv.domainmodel.Driver driver,
        java.lang.String category) {
        super();
        this.driver = driver;
        this.category = category;
    }

    public DriverCategory() {
        super();
    }
}
