package example.nz.org.take.compiler.userv.spec;

/**
 * Class generated by the take compiler.
 * This class represents the external fact store DP_00x
 * for the predicate specialLocation
 * @version Sun Oct 21 23:25:20 NZDT 2007
 */
public interface ExternalFactStore4specialLocation {
    // Get all instances of this type from the fact store. 
    public nz.org.take.rt.ResourceIterator<example.nz.org.take.compiler.userv.spec.specialLocation> fetch(
        example.nz.org.take.compiler.userv.domainmodel.Driver slot1);
}
