package example.nz.org.take.compiler.userv.spec;

/**
 * Class generated by the take compiler.
 * This class represents the predicate isHighRiskDriver
 * @version Thu Oct 18 23:01:31 NZDT 2007
 */
public class HighRiskDriver {
    public example.nz.org.take.compiler.userv.domainmodel.Driver driver;

    public HighRiskDriver(
        example.nz.org.take.compiler.userv.domainmodel.Driver driver) {
        super();
        this.driver = driver;
    }

    public HighRiskDriver() {
        super();
    }
}
