package example.nz.org.take.compiler.userv.spec;

/**
 * Class generated by the take compiler.
 * This class represents the predicate isLongTermClient
 * @version Sun Oct 21 23:25:20 NZDT 2007
 */
public class LongTermClient {
    public example.nz.org.take.compiler.userv.domainmodel.Driver driver;

    public LongTermClient(
        example.nz.org.take.compiler.userv.domainmodel.Driver driver) {
        super();
        this.driver = driver;
    }

    public LongTermClient() {
        super();
    }
}
