package example.nz.org.take.compiler.userv.spec;

/**
 * Class generated by the take compiler.
 * This class represents the predicate specialLocation
 * @version Sun Oct 21 23:25:20 NZDT 2007
 */
public class specialLocation {
    public example.nz.org.take.compiler.userv.domainmodel.Driver slot1;

    public specialLocation(
        example.nz.org.take.compiler.userv.domainmodel.Driver slot1) {
        super();
        this.slot1 = slot1;
    }

    public specialLocation() {
        super();
    }
}
