package example.nz.org.take.compiler.userv.spec;

/**
 * Class generated by the take compiler.
 * This class represents the predicate hasTrainingCertification
 * @version Sun Oct 21 23:25:19 NZDT 2007
 */
public class TrainedDriver {
    public example.nz.org.take.compiler.userv.domainmodel.Driver driver;

    public TrainedDriver(
        example.nz.org.take.compiler.userv.domainmodel.Driver driver) {
        super();
        this.driver = driver;
    }

    public TrainedDriver() {
        super();
    }
}
