package test.nz.org.take.compiler.scenario0.generatedclasses;

/**
 * Class generated by the take compiler.
 * This class represents the predicate father
 * @version Wed Jul 29 22:27:06 NZST 2009
 */
public class father {
    public java.lang.String son;
    public java.lang.String father;

    public father(java.lang.String son, java.lang.String father) {
        super();
        this.son = son;
        this.father = father;
    }

    public father() {
        super();
    }
}
