/*
 * Copyright (C) 2006 <A href="http://www-ist.massey.ac.nz/JBDietrich" target="_top">Jens Dietrich</a>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package nz.org.take.compiler;

import java.util.List;

import nz.org.take.KnowledgeBase;



/**
 * Compiler interface. Generates classes for a kb.
 * @author <a href="http://www-ist.massey.ac.nz/JBDietrich/">Jens Dietrich</a>
 */

public interface Compiler {
	
	/**
	 * Specify whether annotations should be added automatically.
	 * @param boolean v
	 */
	public void setAutoAnnotate(boolean v);
	/**
	 * Indicates  whether annotations are added automatically.
	 * @return boolean
	 */
	public boolean isAutoAnnotate();
		
	/**
	 * Compile the kb with the list of queries in the kb.
	 * @param kb a knowledge base
	 * @throws CompilerException
	 */
	public void compile (KnowledgeBase kb) throws CompilerException ;
	/**
	 * Create a public interface for the knowlegde base.
	 * This method will create an interface containing the public methods of the kb to be generated by the kb.
	 * it will also create the referenced types - the data types for the predicates referenced in the queries.
	 * @param kb a knowledge base
	 * @throws CompilerException
	 */
	public void compileInterface (KnowledgeBase kb) throws CompilerException ;
	/**
	 * Get the name generator.
	 * @return Returns the nameGenerator.
	 */
	public NameGenerator getNameGenerator();
	/**
	 * Set the name generator.
	 * @param nameGenerator The nameGenerator to set.
	 */
	public void setNameGenerator(NameGenerator nameGenerator);
	/**
	 * Get the package name for the code to generate.
	 * @return Returns the package name.
	 */
	public String getPackageName();
	/**
	 * Set the package name for the code to generate.
	 * @param packageName the package name.
	 */
	public void setPackageName(String packageName);
	/**
	 * Get the name of the class to generate.
	 * @return a class name.
	 */
	public String getClassName();
	/**
	 * Set the class name for the code to generate.
	 * @param className the class name.
	 */
	public void setClassName(String className);
	/**
	 * Get the location used to generate and compile code.
	 * @return a location.
	 */
	public Location getLocation();
	/**
	 * Set the location used to generate and compile code.
	 * @param location  the location.
	 */
	public void setLocation(Location location);
	/**
	 * Get the (fully qualified) names of  interfaces to be implemented by the generated kb class.
	 * Can be null (no interfaces)
	 * @return Returns interface names.
	 */
	public String[] getInterfaceNames();
	/**
	 * Set the import statements (without ; at the end) to be used in the generated kb class.
	 * @param names the names.
	 */
	public void setImportStatements(String... statements);
	/**
	 * Get the import statements (without ; at the end) to be used in the generated kb class.
	 * Can be null (no imports)
	 * @return Returns import statements.
	 */
	public String[] getImportStatements();
	/**
	 * Set the (fully qualified) names of  interfaces to be implemented by the generated kb class.
	 * @param names the names.
	 */
	public void setInterfaceNames(String... names);
	/**
	 * Add a source code transformer.
	 * @param a transformer
	 */
	public void add(SourceTransformation transformer);
	/**
	 * Remove a source code transformer.
	 * @param a transformer
	 */
	public void remove(SourceTransformation transformer);
	/**
	 * Get a list of source transformers installed.
	 * @return a list of transformations
	 */
	public List<SourceTransformation> getSourceTransformers();
	/**
	 * Generate data classes for predicates used in queries. If set to false, a package should be imported that contains the 
	 * already generated classes. This is usually used if a separete interface is generated. 
	 * @param value true or false
	 */
	public void setGenerateDataClassesForQueryPredicates(boolean value);
	/**
	 * Whether to generate data classes for predicates used in queries. If set to false, a package should be imported that contains the 
	 * already generated classes. This is usually used if a separete interface is generated. 
	 * @return true or false, the default should be true
	 */
	public boolean isGenerateDataClassesForQueryPredicates();
}
