package example.nz.org.take.compiler.userv.spec.impl_v071107_203954;

/**
 * Class generated by the take compiler.
 * This class represents the predicate includesUninsuredMotoristCoverage
 * @version Wed Nov 07 20:39:55 NZDT 2007
 */
public class includesUninsuredMotoristCoverage {
    public example.nz.org.take.compiler.userv.domainmodel.Policy slot1;

    public includesUninsuredMotoristCoverage(
        example.nz.org.take.compiler.userv.domainmodel.Policy slot1) {
        super();
        this.slot1 = slot1;
    }

    public includesUninsuredMotoristCoverage() {
        super();
    }
}
