package example.nz.org.take.compiler.userv.spec.impl_v071107_203954;

/**
 * Class generated by the take compiler.
 * This class represents the predicate isSedan
 * @version Wed Nov 07 20:39:56 NZDT 2007
 */
public class isSedan {
    public example.nz.org.take.compiler.userv.domainmodel.Car slot1;

    public isSedan(example.nz.org.take.compiler.userv.domainmodel.Car slot1) {
        super();
        this.slot1 = slot1;
    }

    public isSedan() {
        super();
    }
}
