package example.nz.org.take.compiler.userv.spec.impl_v071107_203954;

/**
 * Class generated by the take compiler.
 * This class represents the predicate less_than_or_equal_ii
 * @version Wed Nov 07 20:39:55 NZDT 2007
 */
public class less_than_or_equal_ii {
    public int slot1;
    public int slot2;

    public less_than_or_equal_ii(int slot1, int slot2) {
        super();
        this.slot1 = slot1;
        this.slot2 = slot2;
    }

    public less_than_or_equal_ii() {
        super();
    }
}
