package example.nz.org.take.compiler.userv.spec.impl_v071107_203954;

/**
 * Class generated by the take compiler.
 * This class represents the predicate isEligible
 * @version Wed Nov 07 20:39:55 NZDT 2007
 */
public class not_DriverEligibility {
    public example.nz.org.take.compiler.userv.domainmodel.Driver driver;

    public not_DriverEligibility(
        example.nz.org.take.compiler.userv.domainmodel.Driver driver) {
        super();
        this.driver = driver;
    }

    public not_DriverEligibility() {
        super();
    }
}
