/**
 * Copyright 2007 Jens Dietrich Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 
 * Unless required by applicable law or agreed to in writing, software distributed under the 
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, 
 * either express or implied. See the License for the specific language governing permissions 
 * and limitations under the License.
 */

package nz.org.take.mandarax_migration_kit;


import java.beans.XMLEncoder;
import java.io.File;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.util.Map;
import org.apache.log4j.Category;

/**
 * Constant handlers are used to deal with the constants found in the
 * mandarax kb. These objects are represented by strings in the script
 * generated. This handler serialises these objects using standard JDK XML
 * serialization (for beans) and also generates a script that can be used
 * to read these objects.
 * @author Jens Dietrich
 */

public class XMLConstantHandler implements ConstantHandler {

	public void generateScript(File folder, Map<String, Object> constants,Category logger) throws Exception {
		// write objects
		logger.info("Serializing objects found in mandarax kb using XML serialization to objects.xml");
		File f = new File(folder.getAbsolutePath() + File.separatorChar + "objects.xml");
		FileOutputStream fout = new FileOutputStream(f);
		XMLEncoder encoder = new XMLEncoder(fout);
		boolean generateScript = true;
		try {
			encoder.writeObject(constants);
		}
		catch (Exception t) {
			generateScript = false;
			logger.error("Error serializing oject references found in knowledge base - use alternative constant handler", t);
		}
		finally {
			encoder.close();
		}
		
		if (!generateScript)
			return;
		
		// generate script to recover objects
		logger.info("Creating script to load objects: recoverobjectsscript.txt");
		f = new File(folder.getAbsolutePath() + File.separatorChar + "recoverobjectsscript.txt");
		PrintStream out = new PrintStream(new FileOutputStream(f));
		out.println("// script that can be used to recover the objects found in the (mandarax) knowledge base");
		out.println("// applications should initialise the Constants class generated by the TAKE compiler with these objects ");
		out.println("FileInputStream in = new FileInputStream(\"objects.xml\")");
		out.println("XMLDecoder decoder = new XMLDecoder(in);");
		out.println("Map<String, Object> r = (Map<String, Object>)decoder.readObject();");
		out.println("out.close();");
		out.close();
		
	}

}
