package example.nz.org.take.compiler.example1.impl;
/**
 * Class generated by the take compiler. 
 * This class holds the constants referenced in the knowledge base. 
 * @version Mon May 21 14:02:11 NZST 2007
 */
@SuppressWarnings("unchecked")
public class Constants{
public static test.nz.org.take.compiler.scenario6.Person Werner;
public static test.nz.org.take.compiler.scenario6.Person Ralf;
public static test.nz.org.take.compiler.scenario6.Person Guenther;
public static test.nz.org.take.compiler.scenario6.Person Klaus;
public static test.nz.org.take.compiler.scenario6.Person Jens;
public static test.nz.org.take.compiler.scenario6.Person Max;
public static test.nz.org.take.compiler.scenario6.Person Otto;
public static test.nz.org.take.compiler.scenario6.Person Lutz;
public static test.nz.org.take.compiler.scenario6.Person Frank;
}
