package example.nz.org.take.compiler.userv.spec.impl_v071107_203954;
/**
 * Class generated by the take compiler. 
 * This class holds the constants referenced in the knowledge base. 
 * @version Wed Nov 07 20:39:54 NZDT 2007
 */
@SuppressWarnings("unchecked")
public class Constants{
public static java.util.Collection HighTheftProbabilityAutoList;
public static int NextYear;
public static int CurrentYear;
}
