package example.nz.org.take.compiler.userv.spec.impl_v071107_203954;

/**
 * Class generated by the take compiler.
 * This class represents the predicate contains
 * @version Wed Nov 07 20:39:55 NZDT 2007
 */
public class contains {
    public java.util.Collection slot1;
    public java.lang.Object slot2;

    public contains(java.util.Collection slot1, java.lang.Object slot2) {
        super();
        this.slot1 = slot1;
        this.slot2 = slot2;
    }

    public contains() {
        super();
    }
}
