package example.nz.org.take.compiler.userv.spec.impl_v071107_203954;
/**
 * Class generated by the take compiler. 
 * This class holds the fact stores referenced in the knowledge base. 
 * @version Wed Nov 07 20:39:55 NZDT 2007
 */
@SuppressWarnings("unchecked")
public class FactStores{
public static example.nz.org.take.compiler.userv.spec.ExternalFactStore4specialLocation DP_00x=null;
public static example.nz.org.take.compiler.userv.spec.ExternalFactStore4hasBeenConvictedOfaDUI DRCx=null;
}
