package example.nz.org.take.compiler.userv.spec.impl_v071107_203954;

/**
 * Class generated by the take compiler.
 * This class represents the predicate hasAirbags
 * @version Wed Nov 07 20:39:55 NZDT 2007
 */
public class not_hasAirbags {
    public example.nz.org.take.compiler.userv.domainmodel.Car slot1;

    public not_hasAirbags(
        example.nz.org.take.compiler.userv.domainmodel.Car slot1) {
        super();
        this.slot1 = slot1;
    }

    public not_hasAirbags() {
        super();
    }
}
