/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package nz.org.take.script.parser;

public interface ParserConstants {

  int EOF = 0;
  int DOT = 5;
  int EQ = 6;
  int COL = 7;
  int VAR = 8;
  int NOT = 9;
  int REF = 10;
  int AND = 11;
  int IF = 12;
  int THEN = 13;
  int QUERY = 14;
  int EXTERNAL = 15;
  int IN = 16;
  int OUT = 17;
  int AGGREGATION = 18;
  int SUM = 19;
  int MAX = 20;
  int MIN = 21;
  int AVG = 22;
  int COUNT = 23;
  int COMMENT = 24;
  int GLOBALANNOTATION = 25;
  int LOCALANNOTATION = 26;
  int INTEGER_NUMBER = 27;
  int DECIMAL_NUMBER = 28;
  int LABEL = 29;
  int NAME = 30;
  int STRING_LITERAL = 31;
  int WHITESPACE = 32;
  int SEMICOLON = 33;
  int COMMA = 34;
  int COMPARISON = 35;
  int ARITHMETICOPERATION = 36;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\".\"",
    "\"=\"",
    "\":\"",
    "\"var\"",
    "\"not\"",
    "\"ref\"",
    "\"and\"",
    "\"if\"",
    "\"then\"",
    "\"query\"",
    "\"external\"",
    "\"in\"",
    "\"out\"",
    "\"aggregation\"",
    "\"sum\"",
    "\"max\"",
    "\"min\"",
    "\"avg\"",
    "\"count\"",
    "<COMMENT>",
    "<GLOBALANNOTATION>",
    "<LOCALANNOTATION>",
    "<INTEGER_NUMBER>",
    "<DECIMAL_NUMBER>",
    "<LABEL>",
    "<NAME>",
    "<STRING_LITERAL>",
    "<WHITESPACE>",
    "\";\"",
    "\",\"",
    "<COMPARISON>",
    "<ARITHMETICOPERATION>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
  };

}
