/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package nz.org.take.script.parser;

public interface ParserConstants {

  int EOF = 0;
  int DOT = 5;
  int EQ = 6;
  int COL = 7;
  int VAR = 8;
  int AND = 9;
  int IF = 10;
  int THEN = 11;
  int QUERY = 12;
  int IN = 13;
  int OUT = 14;
  int GLOBALANNOTATION = 15;
  int LOCALANNOTATION = 16;
  int INTEGER_NUMBER = 17;
  int DECIMAL_NUMBER = 18;
  int LABEL = 19;
  int NAME = 20;
  int COMMENT = 21;
  int STRING_LITERAL = 22;
  int WHITESPACE = 23;
  int SEMICOLON = 24;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\".\"",
    "\"=\"",
    "\":\"",
    "\"var\"",
    "\"and\"",
    "\"if\"",
    "\"then\"",
    "\"query\"",
    "\"in\"",
    "\"out\"",
    "<GLOBALANNOTATION>",
    "<LOCALANNOTATION>",
    "<INTEGER_NUMBER>",
    "<DECIMAL_NUMBER>",
    "<LABEL>",
    "<NAME>",
    "<COMMENT>",
    "<STRING_LITERAL>",
    "<WHITESPACE>",
    "\";\"",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
